"""
Empirically discovered required fields for Tripletex API endpoints.
Generated by scripts/scan_required_fields.py — re-run to refresh.
"""

REQUIRED_FIELDS: dict[str, list[str]] = {
    "POST /employee": ["firstName", "lastName"],
    "POST /customer": ["name"],
    "POST /product": ["name"],
    "POST /order": ["deliveryDate", "orderDate", "customer"],
    "POST /invoice": ["orders", "invoiceDate", "invoiceDueDate"],
    "POST /travelExpense": ["employee"],
    "POST /project": [],
    "POST /department": ["name"],
    "POST /ledger/voucher": ["date", "description", "postings"],
    "POST /supplier": ["name"],
    "POST /supplierInvoice": ["invoiceDate"],
    "POST /purchaseOrder": ["supplier", "ourContact", "deliveryDate"],
    "POST /timesheet/entry": ["activity", "employee", "date"],
    "POST /salary/type": [],
}
